In [1]:
import numpy as np

#### a)

In [2]:
'''
Uma abordagem pra resolver é considerar cada susuwatari dividido 
como 1/2 da massa do susuwatari anterior. Dessa forma se ele for
divido 1x passará a ser 2 susuwataris com metade da massa, mas a
soma da massa será igual ao original. Não importa quantas vezes 
o susuwatari original for dividido, a soma da massa de todos 
susuwatari sempre será igual a 1.

Dessa forma conseguimos verificar se a àrea restante da casa
consegue comportar o susuwatari denrtro do quarto. 

Dado isso, podemos mapear a massa possível a ser preenchida pelos
susuwataris no restante da casa e ver se haveria espaço possível 
para comportar susuwataris com o total de massa igual a 1.

A solução é especifica para o estado inicial e as variaveis que
importam são: o tamanho do quarto, a quantidade de susuwataris e
suas posições.
'''

def area_calculator(rows:int,cols:int,room_size:list) -> tuple:
    '''
    Area restante da casa para um tamanho definido de quarto
    e um susuwatari no canto superior esquerdo.
    '''

    matrix = np.empty([rows,cols])

    for i in range(rows):
        for j in range(cols):
            matrix[i,j] = 1/ 2**(i + j)

    
    width,height = room_size
    
    area = 0
    for n in range(rows):
        if n < height:
            area += np.sum(matrix[n,width:])
        else:
            area += np.sum(matrix[n,:])
            
    total_area = np.sum(matrix)
    
    return (matrix,area,total_area)

area_calculator(5,5,[2,2])[0]

array([[1.        , 0.5       , 0.25      , 0.125     , 0.0625    ],
       [0.5       , 0.25      , 0.125     , 0.0625    , 0.03125   ],
       [0.25      , 0.125     , 0.0625    , 0.03125   , 0.015625  ],
       [0.125     , 0.0625    , 0.03125   , 0.015625  , 0.0078125 ],
       [0.0625    , 0.03125   , 0.015625  , 0.0078125 , 0.00390625]])

In [3]:
print(area_calculator(10,10,[3,3])[1])

'''
Cada nova coluna (ou linha) será 1/2 da coluna (ou linha) anterior.
Já que existe a área do quarto que é removida do calculo, não 
importa a quantidade de colunas ou linhas da casa, pois no limite 
a área fora do quarto nunca chega a 1, sempre será adicionado 1/2 
do que foi adicionado na última iteração.
Portanto é impossível retirar o susuwatari do quarto.

Área fora do quarto: 0.9375
'''

print(area_calculator(1000,1000,[3,3])[1])

0.9296913146972656
0.9375


#### b)

In [4]:
'''
Para um grid 2021×2021:
Vimos em a) que não é possível tirar um susuwatari de um quarto 3x3.
Para um quarto 2x2 é possível retirar o susuwatari e esse é o menor
quadrado que permite que o problema seja resolvido (com o susuwatari 
no canto superior esquerdo). Nesse grid ainda é possível adicionar 
mais 2 quadrados para baixo ou dois para direita. Podemos ver isso pela 
área do quarto vs a área do restante da casa ao ir transferindo quadrados
do resto da casa para o quarto contanto que a area do restante da casa 
permaneça maior que 1. Mas mesmo assim é impossivel formar um quadrado 
maior que 2x2.

Area da casa = 4
Area do casa fora o quarto = 1.75
Massa do susuwatari no canto superior esquerdo = 1
Area sobrando fora do quarto = 0.75

'''

print(area_calculator(1000,1000,[2,2])[1:],'\n',area_calculator(5,5,[2,2])[0])

(1.75, 4.0) 
 [[1.         0.5        0.25       0.125      0.0625    ]
 [0.5        0.25       0.125      0.0625     0.03125   ]
 [0.25       0.125      0.0625     0.03125    0.015625  ]
 [0.125      0.0625     0.03125    0.015625   0.0078125 ]
 [0.0625     0.03125    0.015625   0.0078125  0.00390625]]


In [5]:
'''
Dado que no grid 3x3 não é possível retirar o susuwatari do canto
superior esquerdo do quarto, a area de 2021×2021 pode ser reduzida
por duas linhas de largura 2, uma horizontal e uma vertical.
Como no exemplo a seguir.
'''

efective_area = np.zeros([10,10])

efective_area[:,8:] = 1
efective_area[8:,:] = 1

efective_area[9,9] = 2

efective_area

array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 2.]])

In [6]:
'''
Qualquer susuwatari que estiver distante do canto inferior direito 
da matriz (ponto 2) irá se dividir e obrigatóriamente irá sair por
esse ponto de alguma forma. Se o susuwatari estiver na linha
vertical ele se dividirá descendo até chegar em 2 e se estiver na
linha horizonal irá se dividir até a direta até chegar em 2.
Desse modo o problema passa a ser quantos susuwatari consigo remover
pelo ponto 2 antes de travar o resto da casa e não conseguir remover
mais nenhum.
'''


'''
Se olharmos agora um corte do resto da casa e apenas o ponto 2 do 
quarto no canto superior esquerdo, podemos tentar calcular quantos 
susuwatari saindo pelo ponto 2 a casa consegue suportar. A questão é que 
'''

efective_area = np.zeros([5,5])

efective_area[0,0] = 2

print(efective_area)

print(area_calculator(100,100,[1,1])[1:])
print(area_calculator(5,5,[1,1])[0])

[[2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(3.0, 4.0)
[[1.         0.5        0.25       0.125      0.0625    ]
 [0.5        0.25       0.125      0.0625     0.03125   ]
 [0.25       0.125      0.0625     0.03125    0.015625  ]
 [0.125      0.0625     0.03125    0.015625   0.0078125 ]
 [0.0625     0.03125    0.015625   0.0078125  0.00390625]]


In [7]:
'''
Dessa vez temos a casa com area 4 e o quarto com area 1. Intuitivamente
poderiamos dizer que no resto da casa cabem exatamente 3 susuwataris que
vêm pelo ponto 2 do quarto. 



Porém a primeira linha da casa e a primeira
coluna da casa não podem ser preenchidas completamente pelos susuwataris
que saem pelo ponto 2, fazendo com que a area restante da casa seja menor 
que 3, permitindo que somente 2 susuwataris saiam do quarto.
'''

area_calculator(100,100,[2,2])[1]

1.75

In [8]:
'''
Em questão de posição, os dois susuwataris possíveis podem estár em qualquer
posição das quatro possíveis no quarto 2x2, exceto no canto superior esquerdo.
Pois, se um dos susuwataris está no canto superior esquerdo ele irá se dividir
em mais dois susuwataris dentro do quarto, totalizando 3 susuwataris que devem
sair pelo ponto 2, o que vimes que é impossivel.
'''

room_area = np.ones([2,2])
room_area[1,1] = 2
print(room_area)

[[1. 1.]
 [1. 2.]]
